# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        exclude: "mkdocs.yml"
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: no-commit-to-branch
        args:
          - --pattern=develop|main
    -   id: check-added-large-files
        args:
          - --maxkb=1000
        exclude: "notebooks/*.ipynb"

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args: # Added to the .toml file
                - --line-length=79


-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        args: #Check .flake8
            - --max-line-length=79
            - --max-doc-length=72
            - --ignore=E203,W503,E266,E501,F403,F401,W505

# Remove unused variables
-   repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    -   id: autoflake
        args:
        - --in-place
        - --remove-unused-variables            
        - --remove-all-unused-imports

-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort (python)
        args:
              - --line-length=79
              # - --src=your-src-folder-1 # Edit this----
              # - --src=your-src-folder-2

-   repo: https://github.com/PyCQA/pylint
    rev: v2.13.4
    hooks:
    -   id: pylint
        args:
            - --disable=unused-argument # Prevent some refactoring

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
    -   id: mypy
        additional_dependencies:
          - types-requests
        args:
            - --ignore-missing-imports  

-   repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
    -   id: pydocstyle